### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by tadfisher** [tadfisher/android-sdk-updater#12]
Right now, if the `android` subprocess fails, you get some awesome output like:

```
Querying update sites for available packages...
Traceback (most recent call last):
  File "/home/tad/python/2/bin/android-sdk-updater", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tad/git/android-sdk-updater/bin/android-sdk-updater", line 67, in <module>
    sys.exit(main())
  File "/home/tad/git/android-sdk-updater/bin/android-sdk-updater", line 62, in main
    dry_run=args.dry_run)
  File "/home/tad/git/android-sdk-updater/sdk_updater/update.py", line 117, in main
    available = list_packages(android, options=options, verbose=verbose)
  File "/home/tad/git/android-sdk-updater/sdk_updater/list.py", line 36, in list_packages
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['./tools/android', u'list', u'sdk', u'--all', u'--extended', 'no-https']' returned non-zero exit status 1
```

We should catch this and print the process' `stderr`.

**Comment by tadfisher** [comment]
Another thing: catching `Download interrupted` from `android update sdk` and dumping that to `stderr`.
