### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by IgorGanapolsky** [tadfisher/android-sdk-updater#28]
Hello,
when I run **android-sdk-updater**, I get this error:
> Namespace(android_home=None, dry_run=False, package=[], timeout=0, verbose=False)
Scanning /Users/igorganapolsky/Library/Android/sdk for installed packages...
Package parse failed: cmake
Package parse failed: lldb/2.1
Package parse failed: lldb/2.2
Package parse failed: ndk-bundle
Traceback (most recent call last):
  File "/usr/local/bin/android-sdk-updater", line 5, in <module>
    pkg_resources.run_script('android-sdk-updater==1.0.0', 'android-sdk-updater')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/EGG-INFO/scripts/android-sdk-updater", line 60, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/EGG-INFO/scripts/android-sdk-updater", line 55, in main
    dry_run=args.dry_run)
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/sdk_updater/update.py", line 83, in main
    installed = scan(sdk, verbose=verbose)
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/sdk_updater/scan.py", line 109, in scan
    package = parse(top, root)
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/sdk_updater/scan.py", line 80, in parse
    }.get(parts[0], default)(props, parts)
  File "/Library/Python/2.7/site-packages/android_sdk_updater-1.0.0-py2.7.egg/sdk_updater/scan.py", line 35, in platform_tools
    if props['license'] == 'android-sdk-preview-license':
KeyError: 'license'

**Comment by tadfisher** [comment]
You need to update to the newest version.

**Comment by IgorGanapolsky** [comment]
I am running off your latest commit.  What do you mean?

**Comment by tadfisher** [comment]
Latest is 1.0.3 which ignores the NDK bundle. Your traceback indicates
version 1.0.0, which would fail on parsing the NDK.
