### ISSUE TITLE
Does not work with -preview releases

### ISSUE THREAD

**Issue by msm-code** [tadfisher/android-sdk-updater#31]
Name mangling doesn't seem to acknowledge `-preview` releases.

When I try to install `tools-preview` package I get an error:

```
╭─msm@mercury /home/msm/Projects/xxx
╰─$ android-sdk-updater --android-home build/android/sdk/ tools-preview 
Scanning build/android/sdk/ for installed packages...
    2 packages installed.
Querying update sites for available packages...
    154 packages available.
Installing: tools-preview [25.2.1 rc1]
Re-scanning build/android/sdk/...
FATAL: Finished: 0 packages installed. Failed to install 1 package(s):
     tools-preview [25.2.1 rc1]
```

Running again with -vv:
```
> Installing Archives:
>   Preparing to install archives
>   Downloading Android SDK Tools, revision 25.2.1 rc1
  Installing Android SDK Tools, revision 25.2.1 rc1
    Installed Android SDK Tools, revision 25.2.1 rc199%))
>   Done. 1 package installed.
> FATAL: Finished: 0 packages installed. Failed to install 1 package(s):
>      tools-preview [25.2.1 rc1]
> Re-scanning ....
> Found package "tools [25.2.1 rc1]" in ./tools
> Found package "platform-tools [24.0.1]" in ./platform-tools
Traceback (most recent call last):
  File "./tools/update-sdks", line 20, in <module>
    execute(cmd, sdk)
  File "/home/msm/Projects/xxx/tools/tools.py", line 57, in execute
    raise Exception('command "{}" failed with return code: {}'.format(cmd, process.returncode))
Exception: command "android-sdk-updater --android-home . tools-preview -vv" failed with return code: 1                        
```

What should I do to fix it? Or maybe I should specify package name differently?

**Comment by tadfisher** [comment]
Use the gradle plugin, -preview releases are not available in the normal release channels and are not exposed through the `android list sdk` tool.
